version: '3.8'

services:
  suvichaar-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: suvichaar-fastapi-service-prod
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    env_file:
      - .env.production
    volumes:
      - temp-data:/app/temp
      - logs-data:/app/logs
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    networks:
      - suvichaar-network

networks:
  suvichaar-network:
    driver: bridge

volumes:
  temp-data:
  logs-data:
